### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by juanchocas** [boreq/basilisk#3]
I've placed the "basic" directory (found within the "examples" directory) on my Desktop/web_input directory. I try to generate an output on my Desktop/web_output directory, but I get this error message:
![basilisk_error](https://user-images.githubusercontent.com/57829079/86037798-39e1e400-ba40-11ea-81bf-4aa24c28d16e.png)

I'm on a 2011 iMac, in case that's of any help.

**Comment by boreq** [comment]
Hi, this may be a problem with your Python or pip version. Can you please post the steps that you went through to install basilisk?

It would be helpful if you could post the output of the following commands as well:
```
$ python --version
$ pip --version
```
If you use virtualenvs then please post the output of the aforementioned commands with the virtualenv activated.

For reference here is what I just did in an attempt to replicate your problem:

First I installed basilisk in a fresh virtualenv:
```
$ python --version
Python 3.8.3
$ python -m venv basiliskvenv
$ source basiliskvenv/bin/activate
$ pip install git+https://github.com/boreq/basilisk
$ basilisk --version # just to confirm that it works
```
Then I attempted to build the example website, with the virtualenv still active:
```
$ git clone https://github.com/boreq/basilisk
$ cd basilisk/examples
$ basilisk build basic/ /tmp/output
```

I will try to replicate this problem on a mac tomorrow but I am guessing it is most likely related to a pip or Python version as I said.

**Comment by juanchocas** [comment]
I've now re-tested this with a linux box I have in which I've set the default python version to be 3.7 and it worked just fine, so it seems to me like your guess is completely accurate. Thanks for the support!
